# conda env create --file environment.yml
name: musical_analysis
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
- cookiecutter
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - pip
  - pyprojroot
  - python=>=3.8.1,<3.12
  - pip:
    - pyhere
    